version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres-casa-hamburguer

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10203040
      POSTGRES_DB: casa-do-hamburguer

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
